# Generated by Django 6.0 on 2026-02-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_lessonprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="codigo_meta",
            field=models.CharField(default="tutti frutti", max_length=100),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lumi_tip",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="objetivo_texto",
            field=models.CharField(
                default="¡Logra que aparezca el mensaje!", max_length=250
            ),
        ),
    ]
