# Generated by Django 6.0 on 2026-02-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_lesson_codigo_meta_lesson_lumi_tip_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="objetivo_texto",
        ),
        migrations.AddField(
            model_name="lesson",
            name="objetivo_1",
            field=models.CharField(
                default="Escribe 'print' en minúsculas.", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="objetivo_2",
            field=models.CharField(
                default="Añade tu nombre dentro de comillas.", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="objetivo_3",
            field=models.CharField(default="¡Haz clic en Ejecutar!", max_length=200),
        ),
    ]
