# Generated by Django 6.0 on 2026-02-04 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="achievement",
            options={
                "verbose_name": "Catálogo de Logro",
                "verbose_name_plural": "Catálogo de Logros",
            },
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="points_awarded",
        ),
        migrations.AddField(
            model_name="achievement",
            name="xp_reward",
            field=models.IntegerField(default=50, verbose_name="XP de Regalo"),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="description",
            field=models.TextField(verbose_name="¿Cómo se consigue?"),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="icon_name",
            field=models.CharField(
                default="emoji_events",
                help_text="Nombre en Material Symbols",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre del Logro"),
        ),
        migrations.AlterField(
            model_name="userachievement",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achievements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userachievement",
            unique_together={("user", "achievement")},
        ),
    ]
