# Generated by Django 6.0 on 2026-02-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_achievement_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="min_level",
            field=models.IntegerField(default=1),
        ),
    ]
