# Generated by Django 6.0 on 2026-02-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_course_min_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.CharField(
                choices=[
                    ("all", "Todo"),
                    ("variables", "Variables"),
                    ("logica", "Lógica"),
                    ("loops", "Bucles"),
                    ("funciones", "Funciones"),
                ],
                default="all",
                max_length=20,
            ),
        ),
    ]
