# Generated by Django 6.0 on 2026-02-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_course_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.CharField(default="gumi", max_length=20),
        ),
        migrations.AddField(
            model_name="profile",
            name="nickname",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.CharField(
                choices=[
                    ("all", "🌟 Todos los Módulos"),
                    ("variables", "📦 Variables y Datos"),
                    ("logica", "🛤️ Lógica (If/Else)"),
                    ("loops", "🔁 Bucles (Loops)"),
                    ("funciones", "🧩 Funciones"),
                ],
                default="all",
                max_length=20,
                verbose_name="Categoría de Python",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="color",
            field=models.CharField(
                default="blue",
                help_text="Ej: blue, purple, green, yellow",
                max_length=20,
            ),
        ),
    ]
