# Generated by Django 6.0 on 2026-02-04 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_mission_usermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instructions", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="OpenQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="mission",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="mission",
            name="mission_type",
            field=models.CharField(
                choices=[
                    ("quiz", "Quiz"),
                    ("question", "Pregunta"),
                    ("code", "Código"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="code_exercise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.codeexercise",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.openquestion",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="quiz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.quiz",
            ),
        ),
    ]
