# Generated by Django 6.0 on 2026-02-05 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_codeexercise_openquestion_quiz_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mission",
            name="code_exercise",
        ),
        migrations.AlterUniqueTogether(
            name="lessonprogress",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="lessonprogress",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="lessonprogress",
            name="user",
        ),
        migrations.RemoveField(
            model_name="mission",
            name="question",
        ),
        migrations.RemoveField(
            model_name="mission",
            name="quiz",
        ),
        migrations.AddField(
            model_name="mission",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="missions",
                to="core.lesson",
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="xp_reward",
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="course",
            name="color",
            field=models.CharField(
                default="blue",
                help_text="Ej: blue, pink, green, yellow, purple",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="codigo_meta",
            field=models.CharField(
                default="tutti frutti",
                help_text="Lo que debe imprimir el código",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="content",
            field=models.TextField(help_text="Explicación teórica de la lección"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usermission",
            unique_together={("user", "mission")},
        ),
        migrations.DeleteModel(
            name="CodeExercise",
        ),
        migrations.DeleteModel(
            name="LessonProgress",
        ),
        migrations.DeleteModel(
            name="OpenQuestion",
        ),
        migrations.DeleteModel(
            name="Quiz",
        ),
    ]
