# Generated by Django 6.0 on 2026-02-05 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_remove_mission_code_exercise_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                (
                    "icono",
                    models.CharField(
                        default="bolt",
                        help_text="Nombre en Google Symbols",
                        max_length=50,
                    ),
                ),
                (
                    "color_fondo",
                    models.CharField(
                        choices=[
                            ("pastel-blue", "Azul"),
                            ("pastel-pink", "Rosa"),
                            ("yellow-100", "Amarillo"),
                            ("green-100", "Verde"),
                        ],
                        default="pastel-blue",
                        max_length=50,
                    ),
                ),
                ("xp_recompensa", models.IntegerField(default=50)),
                ("esta_activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="RetoCompletado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_completado", models.DateTimeField(auto_now_add=True)),
                (
                    "reto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.reto"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "reto")},
            },
        ),
    ]
