# Generated by Django 6.0 on 2026-02-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_reto_retocompletado"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reto",
            options={
                "verbose_name": "Reto Mágico",
                "verbose_name_plural": "Retos Mágicos",
            },
        ),
        migrations.RemoveField(
            model_name="reto",
            name="color_fondo",
        ),
        migrations.RemoveField(
            model_name="reto",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="reto",
            name="esta_activo",
        ),
        migrations.RemoveField(
            model_name="reto",
            name="icono",
        ),
        migrations.RemoveField(
            model_name="reto",
            name="titulo",
        ),
        migrations.RemoveField(
            model_name="reto",
            name="xp_recompensa",
        ),
        migrations.AddField(
            model_name="reto",
            name="opciones_o_respuesta",
            field=models.TextField(
                blank=True,
                help_text="Si es quiz: opcion1,opcion2. Si es pregunta: la respuesta.",
            ),
        ),
        migrations.AddField(
            model_name="reto",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("quiz", "Quiz (Opciones)"),
                    ("pregunta", "Pregunta Abierta"),
                    ("terminal", "Ir a la Terminal"),
                ],
                default="quiz",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="reto",
            name="url_destino",
            field=models.CharField(
                default="terminal", help_text="Solo si es tipo Terminal", max_length=200
            ),
        ),
    ]
