# Generated by Django 6.0 on 2026-02-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_reto_options_remove_reto_color_fondo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reto",
            options={},
        ),
        migrations.RemoveField(
            model_name="reto",
            name="url_destino",
        ),
        migrations.AddField(
            model_name="reto",
            name="color_fondo",
            field=models.CharField(default="pastel-blue", max_length=50),
        ),
        migrations.AddField(
            model_name="reto",
            name="descripcion",
            field=models.TextField(default="Describe aquí la misión mágica"),
        ),
        migrations.AddField(
            model_name="reto",
            name="esta_activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="reto",
            name="icono",
            field=models.CharField(default="terminal", max_length=50),
        ),
        migrations.AddField(
            model_name="reto",
            name="titulo",
            field=models.CharField(default="Sin título", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reto",
            name="xp_recompensa",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="reto",
            name="opciones_o_respuesta",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="reto",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("terminal", "Terminal"),
                    ("pregunta", "Pregunta"),
                    ("quiz", "Quiz"),
                ],
                max_length=20,
            ),
        ),
    ]
