# Generated by Django 6.0 on 2026-02-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_reto_options_remove_reto_url_destino_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="example_code",
            field=models.TextField(
                blank=True,
                help_text="Código de ejemplo que aparecerá en un cuadro resaltado",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="image_theory",
            field=models.ImageField(
                blank=True,
                help_text="Imagen para ilustrar la teoría",
                null=True,
                upload_to="lessons/",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="subtitle",
            field=models.CharField(
                blank=True, help_text="Ej: ¡Aprendiendo a usar print!", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="codigo_meta",
            field=models.CharField(default="tutti frutti", max_length=100),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="content",
            field=models.TextField(
                help_text="Cuerpo de la lección (puedes usar HTML básico)"
            ),
        ),
    ]
