# Generated by Django 6.0 on 2026-02-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_lesson_example_code_lesson_image_theory_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={},
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="example_code",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="image_theory",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="lumi_tip",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="objetivo_2",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="objetivo_3",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="subtitle",
        ),
        migrations.AddField(
            model_name="lesson",
            name="image_lumi",
            field=models.ImageField(blank=True, null=True, upload_to="lessons/"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="logro_nombre",
            field=models.CharField(default="Experto en Variables", max_length=100),
        ),
        migrations.AddField(
            model_name="lesson",
            name="opcion_correcta",
            field=models.CharField(default='nombre = "Gumi"', max_length=100),
        ),
        migrations.AddField(
            model_name="lesson",
            name="opcion_incorrecta_1",
            field=models.CharField(default="gumi = bear", max_length=100),
        ),
        migrations.AddField(
            model_name="lesson",
            name="opcion_incorrecta_2",
            field=models.CharField(default='"Gumi" = nombre', max_length=100),
        ),
        migrations.AddField(
            model_name="lesson",
            name="quiz_pregunta",
            field=models.CharField(
                default="¿Cómo guardarías el nombre en una variable?", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="subtitle_teoria",
            field=models.CharField(
                default="¡Las variables son cajas mágicas!", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="content",
            field=models.TextField(help_text="Texto principal de la lección"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="objetivo_1",
            field=models.CharField(default="Escribe 'print'...", max_length=200),
        ),
    ]
