# Generated by Django 6.0 on 2026-02-06 00:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_lesson_options_remove_lesson_example_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="level",
        ),
        migrations.AddField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="courses/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="cursos_inscritos",
            field=models.ManyToManyField(
                blank=True, related_name="estudiantes", to="core.course"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.CharField(
                choices=[("gumi", "Gumi (Osito)"), ("lumi", "Lumi (Conejo)")],
                default="gumi",
                max_length=10,
            ),
        ),
    ]
