# Generated by Django 6.0 on 2026-02-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_comentario_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="logro_nombre",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="objetivo_1",
        ),
        migrations.AddField(
            model_name="lesson",
            name="flag_secreta",
            field=models.CharField(default="GUMI{HOLA_MUNDO}", max_length=100),
        ),
        migrations.AddField(
            model_name="lesson",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="is_bonus",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lesson",
            name="xp_leccion",
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="codigo_meta",
            field=models.CharField(default="print", max_length=100),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="content",
            field=models.TextField(help_text="Texto principal de la misión/lección"),
        ),
    ]
