# Generated by Django 6.0 on 2026-02-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_remove_lesson_logro_nombre_remove_lesson_objetivo_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="objetivo_1",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
