# Generated by Django 6.0 on 2026-02-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_lesson_objetivo_1"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="lumi_tip",
            field=models.TextField(
                blank=True,
                help_text="Consejo que dará Gumi/Lumi si el usuario falla mucho",
                null=True,
            ),
        ),
    ]
