# Generated by Django 6.0 on 2026-02-07 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_lesson_lumi_tip"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="achievement",
            options={
                "ordering": ["curso", "order"],
                "verbose_name": "Catálogo de Logro",
                "verbose_name_plural": "Catálogo de Logros",
            },
        ),
        migrations.AddField(
            model_name="achievement",
            name="curso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logros",
                to="core.course",
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="order",
            field=models.IntegerField(default=1),
        ),
    ]
