# Generated by Django 6.0 on 2026-02-08 04:47

import django.db.models.deletion
import django.db.models.fields.related
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_achievement_options_achievement_curso_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reto",
            name="es_case_sensitive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reto",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reto",
            name="pista",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reto",
            name="color_fondo",
            field=models.CharField(default="pink-100", max_length=50),
        ),
        migrations.AlterField(
            model_name="reto",
            name="descripcion",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="reto",
            name="icono",
            field=models.CharField(default="star", max_length=50),
        ),
        migrations.AlterField(
            model_name="reto",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("terminal", "Terminal Python"),
                    ("pregunta", "Pregunta Abierta"),
                    ("quiz", "Opción Múltiple"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ProgresoReto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completado", models.BooleanField(default=False)),
                ("fecha_completado", models.DateTimeField(auto_now_add=True)),
                (
                    "reto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.reto"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.fields.related.ForeignKey,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "reto")},
            },
        ),
    ]
